[package]
name = "stribog"
version = "0.3.0"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.14", features = ["derive"] }
error-chain = "0.12.4"
walkdir = "2.3.2"
